# Raspberry Pi Camera Capture Configuration

# Camera settings
camera:
  width: 400
  height: 400
  fps: 100
  codec: h264
  container: mkv
  preview: true
  enable_crop: true  # Enable Global Shutter Camera support by default

# Storage settings
storage:
  save_video: true
  output_dir: recordings/
  create_date_folders: true

# Buffer settings
buffer:
  size: 20.0  # seconds
  enabled: true

# Remote control
remote:
  ntfy_topic: raspie-camera-test
  
# LSL settings
lsl:
  stream_name: VideoStream

# Performance settings
performance:
  capture_cpu_core: null
  writer_cpu_core: null
  lsl_cpu_core: null
  ntfy_cpu_core: null

# Audio settings
audio:
  sample_rate: 44100
  channels: 1
  bit_depth: 16
  save_audio: true
  audio_format: wav
  show_preview: false

# Terminal UI settings
terminal:
  colors_enabled: true
  use_unicode: true
  update_frequency: 0.2 