# Raspberry Pi Camera Capture Configuration

# Camera settings
camera:
  width: 400
  height: 400
  fps: 200
  codec: mjpg
  container: mkv
  preview: true  # Enable preview window by default
  enable_crop: auto  # Can be true, false, or auto (detect Global Shutter Camera)

# Storage settings
storage:
  save_video: true
  output_dir: recordings/  # Will be updated with date folder
  create_date_folders: true

# Buffer settings
buffer:
  size: 20.0  # seconds
  enabled: true

# Remote control
remote:
  ntfy_topic: raspie-camera-test
  
# LSL settings
lsl:
  stream_name: VideoStream

# Performance settings
performance:
  capture_cpu_core: null  # null means no specific core assignment
  writer_cpu_core: null
  lsl_cpu_core: null
  ntfy_cpu_core: null

# Audio settings
audio:
  sample_rate: 44100
  channels: 1
  bit_depth: 16
  save_audio: true
  audio_format: wav
  show_preview: false

# Terminal UI settings
terminal:
  colors_enabled: true
  use_unicode: true  # Enable unicode characters for better display
  update_frequency: 0.2  # Update 5 times per second for smooth display 