# IMX296 Global Shutter Camera Configuration
# Author: Anzal KS <anzal.ks@gmail.com>
# Date: May 23, 2025

# System paths and tools
system:
  media_ctl_path: "/usr/bin/media-ctl"
  ffmpeg_path: "/usr/bin/ffmpeg"

# Camera settings
camera:
  # IMX296 camera is 400x400 native resolution in global shutter mode
  width: 400
  height: 400
  fps: 100  # Increased to 100 FPS for high-speed capture
  exposure_time_us: 5000  # 5ms exposure
  
  # GScrop script settings
  script_path: "bin/GScrop"  # Path to GScrop script (relative to project root)
  markers_file: "/dev/shm/camera_markers.txt"  # Markers file for frame timing
  frame_queue_size: 10000  # Size of frame processing queue
  lsl_worker_threads: 1  # Number of LSL worker threads
  
  media_ctl:
    device_pattern: "/dev/media%d"
    entity_pattern: "imx296"
    bayer_format: "SBGGR10_1X10"  # Raw Bayer format for IMX296

# RAM buffer settings for pre-trigger storage
buffer:
  duration_seconds: 5
  max_frames: 500  # Increased to handle higher frame rate

# LSL stream configuration
lsl:
  name: "IMX296Camera"  # Stream name
  type: "VideoEvents"   # Stream type
  id: "cam1"           # Unique identifier

# Recording settings
recording:
  output_dir: "recordings"  # Using local directory instead of system path
  video_format: "mkv"      # Container format (more robust than MP4)
  codec: "mjpeg"          # Use MJPEG codec for better compatibility
  quality: 90             # JPEG quality 0-100

# ntfy.sh notifications for remote control
ntfy:
  server: "https://ntfy.sh"
  topic: "raspie-camera-dawg-123"
  poll_interval_sec: 2

# Logging configuration
logging:
  level: "DEBUG"  # Set to DEBUG for more verbose output
  console: true
  file: "logs/imx296_capture.log"
  max_size_mb: 10
  backup_count: 5 