# IMX296 Global Shutter Camera Configuration
# Author: Anzal KS <anzal.ks@gmail.com>
# Date: May 23, 2025

# System paths and tools
system:
  libcamera_vid_path: "/usr/bin/libcamera-vid"
  libcamera_hello_path: "/usr/bin/libcamera-hello"
  media_ctl_path: "/usr/bin/media-ctl"
  ffmpeg_path: "/usr/bin/ffmpeg"

# Camera settings
camera:
  # Physical sensor specs
  sensor_width: 1456
  sensor_height: 1088
  
  # Target capture specifications
  width: 400  # Match native IMX296 format of 400x400
  height: 400
  fps: 30  # Using 30fps for reliable operation
  exposure_time_us: 8000  # Exposure in microseconds
  
  # PTS file for timestamp tracking
  pts_file_path: "/tmp/imx296_pts.txt"  # Store PTS file in /tmp for best compatibility
  
  # Media-ctl configuration for hardware cropping
  media_ctl:
    device_pattern: "/dev/media%d"
    entity_pattern: "imx296 %d-001a"
    bayer_format: "SBGGR10_1X10"

# RAM buffer settings for pre-trigger storage
buffer:
  duration_seconds: 10
  max_frames: 1000

# LSL stream configuration
lsl:
  stream_name: "IMX296_Metadata"
  stream_type: "CameraEvents"
  channel_count: 4
  nominal_srate: 30

# Recording settings
recording:
  output_dir: "/home/dawg/recordings"  # Using home directory for reliable permissions
  video_format: "mkv"  # MKV container for better compatibility
  codec: "mjpeg"  # MJPEG codec works better than H.264 for IMX296

# ntfy.sh notifications for remote control
ntfy:
  server: "https://ntfy.sh"
  topic: "raspie-camera-dawg-123"  # Unique topic name to avoid conflicts
  poll_interval_sec: 5

# Logging configuration
logging:
  level: "INFO"
  console: true
  file: "logs/imx296_capture.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_size_mb: 10
  backup_count: 5 