# Configuration for IMX296 Global Shutter Camera Capture System
# Author: Anzal KS
# Date: May 22, 2025

# Camera settings
camera:
  # Target resolution and frame rate
  width: 400
  height: 400
  fps: 100
  
  # Original sensor resolution for crop calculation
  sensor_width: 1456
  sensor_height: 1088
  
  # Exposure time in microseconds (9000 is good for 100fps)
  exposure_time_us: 9000
  
  # Media controller settings
  media_ctl:
    device_pattern: "/dev/media%d"  # Use a pattern to allow searching through all devices
    entity_pattern: "imx296 %s-001a"
    bayer_format: "SBGGR10_1X10"  # Format appropriate for IMX296
  
  # PTS file path for timestamp tracking
  pts_file_path: "/tmp/camera_live.pts"

# RAM buffer settings
buffer:
  # Duration in seconds (10-20 seconds recommended)
  duration_seconds: 15
  # Maximum size in frames (as a safety backup)
  max_frames: 1500  # ~15 seconds at 100fps

# Recording settings
recording:
  # Directory where recordings will be stored
  output_dir: "recordings"
  # File format (mkv recommended for robustness)
  format: "mkv"
  # Codec settings for ffmpeg
  codec: "copy"  # Just copy the H.264 stream, no re-encoding

# ntfy.sh notification settings
ntfy:
  server: "https://ntfy.sh"
  topic: "raspie-camera-dawg-123"  # Updated to a unique value
  poll_interval_sec: 30  # Long polling interval

# LSL (Lab Streaming Layer) settings
lsl:
  stream_name: "IMX296_Metadata"
  stream_type: "CameraEvents"
  channel_count: 4  # CaptureTimeUnix, ntfy_notification_active, session_frame_no, trigger_source
  nominal_srate: 100  # Matches camera FPS

# Logging settings
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/imx296_capture.log"
  console: true
  max_size_mb: 10
  backup_count: 5

# System settings
system:
  # Path to libcamera-vid executable
  libcamera_vid_path: "/usr/bin/libcamera-vid"
  # Path to ffmpeg executable
  ffmpeg_path: "/usr/bin/ffmpeg"
  # Path to media-ctl executable
  media_ctl_path: "/usr/bin/media-ctl"
  # Path to libcamera-hello executable (for verification)
  libcamera_hello_path: "/usr/bin/libcamera-hello" 